// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export interface Member {
  id: string
  name: string
  role: string
  aliases: string[]
}

// ---------------------------------------------------------------------------
// Crimes
// ---------------------------------------------------------------------------

export interface Crime {
  id: string
  text: string
  submittedBy: string
  submittedAt: string
  used: boolean
}

// ---------------------------------------------------------------------------
// Evidence
// ---------------------------------------------------------------------------

export type EvidenceType =
  | 'slack'
  | 'linkedin'
  | 'email'
  | 'meeting'
  | 'expense'

export interface Evidence {
  accuserId: string
  accuserName: string
  suspectId: string
  suspectName: string
  prompt: string
  evidenceType: EvidenceType
  generatedEvidence: string
  wordCount: number
  submittedAt: string
}

// ---------------------------------------------------------------------------
// Defense
// ---------------------------------------------------------------------------

export interface Defense {
  defenderId: string
  defenderName: string
  prompt: string
  generatedAlibi: string
  redirectTo: string | null
  wordCount: number
  submittedAt: string
  isAutoGenerated: boolean
}

// ---------------------------------------------------------------------------
// Round
// ---------------------------------------------------------------------------

export type RoundPhase =
  | 'prosecution'
  | 'defense'
  | 'deliberation'
  | 'verdict'
  | 'closed'

export interface Round {
  id: string
  phase: RoundPhase
  crimeId: string
  crimeText: string
  skillIndex: number
  startedAt: string
  defenseDeadline: string | null
  convictId: string | null
}

// ---------------------------------------------------------------------------
// Verdict
// ---------------------------------------------------------------------------

export interface EvidenceScore {
  accuserId: string
  accuserName: string
  suspectId: string
  suspectName: string
  evidenceType: EvidenceType
  promptEfficiency: number
  evidenceQuality: number
  skillUsage: number
  humor: number
  total: number
  reasoning: string
}

export interface Verdict {
  roundId: string
  crimeText: string
  convictId: string
  convictName: string
  winningAccuserId: string
  winningAccuserName: string
  winningEvidence: string
  explanation: string
  skillBreakdown: string
  scores: EvidenceScore[]
  defensePenalty: number
  generatedAt: string
}

// ---------------------------------------------------------------------------
// Confessional
// ---------------------------------------------------------------------------

export interface Confession {
  memberId: string
  text: string
  submittedAt: string
}

// ---------------------------------------------------------------------------
// Criminal Record
// ---------------------------------------------------------------------------

export interface ConvictionEntry {
  roundId: string
  crimeText: string
  convictedBy: string
  winningEvidence: string
  explanation: string
  date: string
  resultId: string
}

export interface CriminalRecord {
  totalConvictions: number
  totalProsecutions: number
  totalWins: number
  currentAlias: string
}

// ---------------------------------------------------------------------------
// Shareable Result
// ---------------------------------------------------------------------------

export interface ShareableResult {
  id: string
  roundId: string
  crimeText: string
  convictId: string
  convictName: string
  convictionCount: number
  winningEvidence: string
  winningAccuserName: string
  explanation: string
  createdAt: string
}

// ---------------------------------------------------------------------------
// Leaderboard
// ---------------------------------------------------------------------------

export interface LeaderboardEntry {
  memberId: string
  memberName: string
  count: number
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface ValidationResult {
  isValid: boolean
  wordCount: number
  reason?: string
}

// ---------------------------------------------------------------------------
// Session (client-side localStorage)
// ---------------------------------------------------------------------------

export interface JailnabiSession {
  memberId: string
  memberName: string
  onboardingComplete: boolean
}

// ---------------------------------------------------------------------------
// SSE Events
// ---------------------------------------------------------------------------

export type StageStatus = 'processing' | 'passed' | 'failed'

export type SSEEvent =
  | { type: 'stage_update'; data: { stage: string; status: StageStatus } }
  | { type: 'validation'; data: ValidationResult }
  | { type: 'evidence_token'; data: { text: string } }
  | { type: 'evidence_complete'; data: { evidence: string; wordCount: number } }
  | { type: 'verdict_token'; data: { text: string } }
  | { type: 'verdict_complete'; data: Verdict }
  | { type: 'result'; data: { resultId: string } }
  | { type: 'error'; data: { message: string } }
