import 'server-only'
import { callClaude } from './claude-client'
import { VERDICT_MODEL } from './constants'
import type { Evidence, Defense, Verdict, EvidenceScore } from './types'
import type { AISkill } from './techniques'

const MAX_VERDICT_TOKENS = 2048

/**
 * Generate a verdict by scoring all evidence, picking a winner,
 * and explaining the prompt technique that made the winning accusation effective.
 */
export async function generateVerdict(
  roundId: string,
  crimeText: string,
  evidence: Evidence[],
  defenses: Record<string, Defense>,
  skill: AISkill,
  onToken?: (token: string) => void
): Promise<Verdict> {
  const evidenceSummary = evidence
    .map(
      (e, i) =>
        `Evidence #${i + 1}:
  Accuser: ${e.accuserName}
  Suspect: ${e.suspectName}
  Type: ${e.evidenceType}
  Prompt (${e.wordCount} words): "${e.prompt}"
  Generated evidence: ${e.generatedEvidence.slice(0, 300)}`
    )
    .join('\n\n')

  const defenseSummary = Object.values(defenses)
    .map(
      (d) =>
        `Defense by ${d.defenderName}${d.isAutoGenerated ? ' (auto-generated — they did not show up)' : ''}:
  Prompt (${d.wordCount} words): "${d.prompt}"
  Alibi: ${d.generatedAlibi.slice(0, 200)}`
    )
    .join('\n\n')

  const systemPrompt = `You are the AI Judge of Jailnabi, a humorous daily accusation game.

You must evaluate all submitted evidence and deliver a verdict. Score each piece of evidence and pick the most convincing accusation.

Crime: "${crimeText}"
Today's AI Skill: "${skill.name}" — "${skill.tip}"

SCORING RUBRIC (visible to players):
- Prompt Efficiency (1-3): Fewer words = higher score
- Evidence Quality (1-3): How convincing/detailed is the generated evidence?
- AI Skill Usage (0-2): Bonus if the prompt demonstrates today's skill "${skill.name}"
- Humor (1-2): How funny is the generated output?
Total per evidence: 3-10

Defenses can subtract up to 2 points from the accusation targeting the defender.

OUTPUT FORMAT — You MUST respond with valid JSON inside <verdict> tags:
<verdict>
{
  "scores": [
    {
      "accuserId": "member-id",
      "accuserName": "Name",
      "suspectId": "suspect-id",
      "suspectName": "Suspect Name",
      "evidenceType": "slack",
      "promptEfficiency": 3,
      "evidenceQuality": 2,
      "skillUsage": 1,
      "humor": 2,
      "total": 8,
      "reasoning": "One sentence explaining the score"
    }
  ],
  "defensePenalty": 1,
  "winnerIndex": 0,
  "explanation": "2-3 sentences explaining the verdict dramatically",
  "skillBreakdown": "2-3 sentences explaining how the winning prompt used (or could have used) today's AI skill"
}
</verdict>

Be dramatic, funny, and educational. The skill breakdown is the core educational payload.`

  const userMessage = `EVIDENCE:\n${evidenceSummary}\n\nDEFENSES:\n${defenseSummary || 'No defenses submitted.'}\n\nDeliver your verdict.`

  const response = await callClaude(
    VERDICT_MODEL,
    systemPrompt,
    userMessage,
    MAX_VERDICT_TOKENS,
    onToken
  )

  // Parse verdict from XML tags
  const match = response.match(/<verdict>([\s\S]*?)<\/verdict>/)
  if (!match) {
    throw new Error('Failed to parse verdict from AI response')
  }

  const parsed = JSON.parse(match[1]) as {
    scores: EvidenceScore[]
    defensePenalty: number
    winnerIndex: number
    explanation: string
    skillBreakdown: string
  }

  // Validate and clamp AI scores to rubric ranges
  for (const score of parsed.scores) {
    score.promptEfficiency = clamp(score.promptEfficiency, 1, 3)
    score.evidenceQuality = clamp(score.evidenceQuality, 1, 3)
    score.skillUsage = clamp(score.skillUsage, 0, 2)
    score.humor = clamp(score.humor, 1, 2)
    score.total = clamp(score.total, 3, 10)
  }
  parsed.defensePenalty = clamp(parsed.defensePenalty, 0, 2)

  const winnerEvidence = evidence[parsed.winnerIndex]
  if (!winnerEvidence) {
    throw new Error('Invalid winner index from AI')
  }

  // Determine the most-accused suspect (the convict)
  const suspectVotes = new Map<string, number>()
  for (const score of parsed.scores) {
    const adjusted =
      score.total - (defenses[score.suspectId] ? parsed.defensePenalty : 0)
    suspectVotes.set(
      score.suspectId,
      (suspectVotes.get(score.suspectId) ?? 0) + adjusted
    )
  }

  let convictId = winnerEvidence.suspectId
  let maxVotes = 0
  for (const [id, votes] of suspectVotes) {
    if (votes > maxVotes) {
      maxVotes = votes
      convictId = id
    }
  }

  const convictName =
    evidence.find((e) => e.suspectId === convictId)?.suspectName ?? 'Unknown'

  const verdict: Verdict = {
    roundId,
    crimeText,
    convictId,
    convictName,
    winningAccuserId: winnerEvidence.accuserId,
    winningAccuserName: winnerEvidence.accuserName,
    winningEvidence: winnerEvidence.generatedEvidence,
    explanation: parsed.explanation,
    skillBreakdown: skill.postVerdictTemplate.replace(
      '{detail}',
      parsed.skillBreakdown
    ),
    scores: parsed.scores,
    defensePenalty: parsed.defensePenalty,
    generatedAt: new Date().toISOString(),
  }

  return verdict
}

function clamp(value: number, min: number, max: number): number {
  const n = Number(value)
  if (!Number.isFinite(n)) return min
  return Math.max(min, Math.min(max, n))
}
