import { describe, it, expect } from 'vitest'
import { parseReport } from '@/lib/visuals/parser'
import { PERSONA_TEMPLATE_CONFIGS } from '@/lib/constants/report-templates'

// ─── Test Data ───

const DOCTOR_REPORT = `# Project Diagnostic Report

**Generated by Full Stack Human AI — The Doctor**

---

## Patient summary

The user described a SaaS product stuck in development for 6 months.

## Diagnosis

**The core problem is a lack of clear product scope.** The team is building features without validating demand.

## Symptoms vs. root cause

| What it looks like | What's actually happening |
| --- | --- |
| "We keep missing deadlines" | Scope creep from undefined product boundaries |
| "The team is demotivated" | No visible progress because success isn't defined |
| "Users aren't engaging" | Building for imagined users, not real ones |

## Risk level

High

If nothing changes in the next 60 days, the runway will shrink to a point where pivoting becomes impossible.

## Recommended actions

1. **Define the MVP scope** — Strip the product to the 3 features that solve the #1 user pain point.
2. **Talk to 10 users this week** — Not surveys. Actual conversations about their workflow.
3. **Kill the roadmap** — Replace it with a 2-week experiment cycle.

## What the AI can't see

- Team dynamics and interpersonal conflicts
- Financial runway details
- The real Francois would run a half-day scope workshop with the founding team

---

_Full Stack Human — The real Francois goes deeper. He'd run a focused scope workshop with your team to align on what actually ships. [Book a call →](https://calendly.com/fullstackhuman)_`

const CRITIC_REPORT = `# Review Brief

**Generated by Full Stack Human AI — The Critic**

---

## What I reviewed

A pitch deck for a B2B SaaS product targeting HR teams.

\`\`\`assessment-radar
{"dimensions": [{"name": "Value Proposition", "score": 7}, {"name": "Market Fit", "score": 5}, {"name": "Technical Depth", "score": 8}, {"name": "Go-to-Market", "score": 3}, {"name": "Team Story", "score": 6}]}
\`\`\`

## What works

The technical depth section is solid. You clearly understand the infrastructure.

## What doesn't work

The go-to-market section reads like an afterthought. No clear channel strategy.

## The thing nobody's telling you

Your biggest risk is not the product. It is that you are building for an audience you have not talked to.

## If I had to prioritize

1. **Fix the GTM narrative** — Your go-to-market section reads like an afterthought.
2. **Add customer validation** — Include 2-3 concrete user quotes or metrics.
3. **Simplify the pricing slide** — Too many tiers confuse investors.

## Where this review stops

- Did not assess financial projections

---

_Full Stack Human — The real Francois goes deeper. [Book a call →](https://calendly.com/fullstackhuman)_`

const GUIDE_REPORT_WITH_FRAMEWORK_MATRIX = `# Framework Brief

**Generated by Full Stack Human AI — The Guide**

---

## What you asked

How should I think about building a product team?

## How to think about this

\`\`\`framework-matrix
{"title": "Team Building Approach", "xAxisLabel": "Structure", "xAxisLow": "Loose", "xAxisHigh": "Rigid", "yAxisLabel": "Autonomy", "yAxisLow": "Low", "yAxisHigh": "High", "quadrants": {"topLeft": {"label": "Startup chaos", "description": "High autonomy, no structure"}, "topRight": {"label": "Empowered teams", "description": "High autonomy within clear guardrails"}, "bottomLeft": {"label": "Drift", "description": "No structure, no direction"}, "bottomRight": {"label": "Command and control", "description": "Rigid processes, low ownership"}}, "userPosition": {"x": 0.3, "y": 0.7}}
\`\`\`

The framework above maps where you are today.

## The reframe

You are not hiring. You are designing a system where good people can do good work.

## Applied to your situation

Start by defining the team operating model before adding headcount.

## What to sit with

What if you already have the right people but the wrong structure?

## Where this goes deeper

- Deep-dive on team operating models
- Framework for role definition

---

_Full Stack Human — The real Francois goes deeper. [Book a call →](https://calendly.com/fullstackhuman)_`

// ─── Doctor Report Parsing ───

describe('parseReport — Doctor', () => {
  it('extracts the title', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    expect(result.title).toBe('Project Diagnostic Report')
  })

  it('strips redundant metadata (Generated by line)', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    expect(result.metadata).toBe('')
  })

  it('parses 6 sections with correct headings', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    expect(result.sections).toHaveLength(6)
    expect(result.sections[0].heading).toContain('Patient summary')
    expect(result.sections[1].heading).toContain('Diagnosis')
    expect(result.sections[2].heading).toContain('Symptoms vs. root cause')
    expect(result.sections[3].heading).toContain('Risk level')
    expect(result.sections[4].heading).toContain('Recommended actions')
    expect(result.sections[5].heading).toContain("What the AI can't see")
  })

  it('extracts CTA footer with Full Stack Human and calendly link', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    expect(result.ctaFooter).toContain('Full Stack Human')
    expect(result.ctaFooter.toLowerCase()).toContain('calendly')
  })

  it('sets persona to doctor', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    expect(result.persona).toBe('doctor')
  })

  it('detects root-cause-flow visual in Symptoms vs root cause section (index 2)', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const signatureSection = result.sections[2]
    expect(signatureSection.visual).not.toBeNull()
    expect(signatureSection.visual!.type).toBe('root-cause-flow')

    const data = signatureSection.visual!.data as {
      rows: Array<{ symptom: string; rootCause: string }>
    }
    expect(data.rows).toHaveLength(3)
    expect(data.rows[0].symptom).toContain('missing deadlines')
    expect(data.rows[0].rootCause).toContain('Scope creep')
  })

  it('detects risk-gauge visual in Risk level section (index 3)', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const riskSection = result.sections[3]
    expect(riskSection.visual).not.toBeNull()
    expect(riskSection.visual!.type).toBe('risk-gauge')

    const data = riskSection.visual!.data as { level: string }
    expect(data.level).toBe('high')
  })

  it('detects priority-roadmap visual in Recommended actions section (index 4)', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const actionsSection = result.sections[4]
    expect(actionsSection.visual).not.toBeNull()
    expect(actionsSection.visual!.type).toBe('priority-roadmap')

    const data = actionsSection.visual!.data as {
      items: Array<{ index: number; label: string; fullText: string }>
    }
    expect(data.items).toHaveLength(3)
    expect(data.items[0].label).toContain('Define the MVP scope')
    expect(data.items[1].label).toContain('Talk to 10 users this week')
    expect(data.items[2].label).toContain('Kill the roadmap')
  })

  it('strips markdown table from root-cause-flow section content', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const signatureSection = result.sections[2]
    // Table source markdown should be stripped when visual is detected
    expect(signatureSection.content).not.toContain('| What it looks like')
    expect(signatureSection.content).not.toContain('| --- |')
    expect(signatureSection.content).not.toContain('missing deadlines')
  })

  it('strips risk level keyword from risk-gauge section content', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const riskSection = result.sections[3]
    // The standalone "High" line should be stripped
    expect(riskSection.content).not.toMatch(/^High$/m)
    // But the elaboration text should remain
    expect(riskSection.content).toContain('nothing changes')
  })

  it('strips numbered list from priority-roadmap section content', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    const actionsSection = result.sections[4]
    // Numbered items should be stripped when visual is detected
    expect(actionsSection.content).not.toContain('1.')
    expect(actionsSection.content).not.toContain('2.')
    expect(actionsSection.content).not.toContain('3.')
  })

  it('does not attach visuals to non-visual sections', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    // Patient summary (index 0) and Diagnosis (index 1) have no visuals
    expect(result.sections[0].visual).toBeNull()
    expect(result.sections[1].visual).toBeNull()
    // What the AI can't see (index 5) has no visual
    expect(result.sections[5].visual).toBeNull()
  })

  it('section indices are sequential starting from 0', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    result.sections.forEach((section, i) => {
      expect(section.index).toBe(i)
    })
  })
})

// ─── Critic Report Parsing ───

describe('parseReport — Critic', () => {
  it('parses 6 sections', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    expect(result.sections).toHaveLength(6)
  })

  it('extracts title', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    expect(result.title).toBe('Review Brief')
  })

  it('strips the assessment-radar fenced block from section content', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    const section0 = result.sections[0]
    // The fenced block JSON should not appear in the content
    expect(section0.content).not.toContain('assessment-radar')
    expect(section0.content).not.toContain('"dimensions"')
  })

  it('attaches assessment-radar visual to section 0 (What I reviewed)', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    const section0 = result.sections[0]
    expect(section0.visual).not.toBeNull()
    expect(section0.visual!.type).toBe('assessment-radar')

    const data = section0.visual!.data as {
      dimensions: Array<{ name: string; score: number }>
    }
    expect(data.dimensions).toHaveLength(5)
    expect(data.dimensions[0].name).toBe('Value Proposition')
    expect(data.dimensions[0].score).toBe(7)
    expect(data.dimensions[4].name).toBe('Team Story')
    expect(data.dimensions[4].score).toBe(6)
  })

  it('detects priority-roadmap in section 4 (If I had to prioritize)', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    const section4 = result.sections[4]
    expect(section4.visual).not.toBeNull()
    expect(section4.visual!.type).toBe('priority-roadmap')

    const data = section4.visual!.data as {
      items: Array<{ label: string }>
    }
    expect(data.items).toHaveLength(3)
  })

  it('extracts CTA footer', () => {
    const result = parseReport(CRITIC_REPORT, 'critic')
    expect(result.ctaFooter).toContain('Full Stack Human')
    expect(result.ctaFooter.toLowerCase()).toContain('calendly')
  })
})

// ─── Guide Report Parsing ───

describe('parseReport — Guide', () => {
  it('parses 6 sections', () => {
    const result = parseReport(GUIDE_REPORT_WITH_FRAMEWORK_MATRIX, 'guide')
    expect(result.sections).toHaveLength(6)
  })

  it('extracts title', () => {
    const result = parseReport(GUIDE_REPORT_WITH_FRAMEWORK_MATRIX, 'guide')
    expect(result.title).toBe('Framework Brief')
  })

  it('attaches framework-matrix visual to section 1 (How to think about this)', () => {
    const result = parseReport(GUIDE_REPORT_WITH_FRAMEWORK_MATRIX, 'guide')
    const section1 = result.sections[1]
    expect(section1.visual).not.toBeNull()
    expect(section1.visual!.type).toBe('framework-matrix')

    const data = section1.visual!.data as {
      title: string
      xAxisLabel: string
      yAxisLabel: string
      quadrants: Record<string, { label: string; description: string }>
      userPosition?: { x: number; y: number }
    }
    expect(data.title).toBe('Team Building Approach')
    expect(data.xAxisLabel).toBe('Structure')
    expect(data.yAxisLabel).toBe('Autonomy')
    expect(data.quadrants.topRight.label).toBe('Empowered teams')
    expect(data.userPosition).toEqual({ x: 0.3, y: 0.7 })
  })

  it('strips the framework-matrix fenced block from content', () => {
    const result = parseReport(GUIDE_REPORT_WITH_FRAMEWORK_MATRIX, 'guide')
    const section1 = result.sections[1]
    expect(section1.content).not.toContain('framework-matrix')
    expect(section1.content).not.toContain('"xAxisLabel"')
    // But the surrounding text should remain
    expect(section1.content).toContain('framework above')
  })

  it('extracts CTA footer', () => {
    const result = parseReport(GUIDE_REPORT_WITH_FRAMEWORK_MATRIX, 'guide')
    expect(result.ctaFooter).toContain('Full Stack Human')
  })
})

// ─── Template Config Consistency ───

describe('PERSONA_TEMPLATE_CONFIGS', () => {
  it('has configs for all three personas', () => {
    expect(PERSONA_TEMPLATE_CONFIGS).toHaveProperty('doctor')
    expect(PERSONA_TEMPLATE_CONFIGS).toHaveProperty('critic')
    expect(PERSONA_TEMPLATE_CONFIGS).toHaveProperty('guide')
  })

  it('doctor signature section is index 2', () => {
    expect(PERSONA_TEMPLATE_CONFIGS.doctor.signatureSectionIndex).toBe(2)
  })

  it('critic signature section is index 3', () => {
    expect(PERSONA_TEMPLATE_CONFIGS.critic.signatureSectionIndex).toBe(3)
  })

  it('guide signature section is index 2', () => {
    expect(PERSONA_TEMPLATE_CONFIGS.guide.signatureSectionIndex).toBe(2)
  })
})

// ─── Edge Cases ───

describe('parseReport — edge cases', () => {
  it('returns empty ctaFooter when no --- CTA footer exists', () => {
    const reportWithoutCta = `# Test Report

**Generated by Test**

---

## Section one

Content here.

## Section two

More content.`

    const result = parseReport(reportWithoutCta, 'doctor')
    expect(result.ctaFooter).toBe('')
  })

  it('returns null visual when fenced block contains malformed JSON', () => {
    const reportWithBadJson = `# Review Brief

**Generated by Test**


---

## What I reviewed

Some content.

\`\`\`assessment-radar
{this is not valid json}
\`\`\`

## What works

Good stuff.

## What doesn't work

Bad stuff.

## The thing nobody's telling you

Secret stuff.

## If I had to prioritize

1. **First thing** — Do this.
2. **Second thing** — Do that.

## Where this review stops

Limits.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(reportWithBadJson, 'critic')
    // Section 0 (What I reviewed) should have null visual because JSON is malformed
    expect(result.sections[0].visual).toBeNull()
    // Content should still be present (fenced block stripped even with bad JSON)
    expect(result.sections[0].content).toContain('Some content')
  })

  it('returns null visual when radar has < 3 dimensions', () => {
    const reportWithFewDimensions = `# Review Brief

**Generated by Test**


---

## What I reviewed

A product.

\`\`\`assessment-radar
{"dimensions": [{"name": "A", "score": 5}, {"name": "B", "score": 3}]}
\`\`\`

## What works

Content.

## What doesn't work

Content.

## The thing nobody's telling you

Content.

## If I had to prioritize

1. **First** — Do this.
2. **Second** — Do that.

## Where this review stops

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(reportWithFewDimensions, 'critic')
    expect(result.sections[0].visual).toBeNull()
  })

  it('returns null risk gauge visual when no risk keyword is found', () => {
    const reportWithNoRisk = `# Project Diagnostic Report

**Generated by Test**

---

## Patient summary

Content.

## Diagnosis

Content.

## Symptoms vs. root cause

| Symptom | Cause |
| --- | --- |
| A | B |

## Risk level

The situation is ambiguous and hard to classify.

## Recommended actions

1. **Action one** — Do this.
2. **Action two** — Do that.

## What the AI can't see

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(reportWithNoRisk, 'doctor')
    expect(result.sections[3].visual).toBeNull()
  })

  it('returns empty sections for empty content', () => {
    const result = parseReport('', 'doctor')
    expect(result.title).toBe('')
    expect(result.sections).toHaveLength(0)
    expect(result.ctaFooter).toBe('')
  })

  it('does not split on ## headings inside fenced code blocks', () => {
    const reportWithCodeBlock = `# Test Report

**Generated by Test**

---

## Patient summary

Here is some code:

\`\`\`markdown
## This heading should not cause a split

Some markdown content.
\`\`\`

The text continues after the code block.

## Diagnosis

Actual second section.

## Symptoms vs. root cause

| A | B |
| --- | --- |
| x | y |

## Risk level

Low

## Recommended actions

1. **First** — A.
2. **Second** — B.

## What the AI can't see

Content.

---

_CTA footer text with calendly link_`

    const result = parseReport(reportWithCodeBlock, 'doctor')
    // Should have 6 sections, not 7 (the ## inside the code block should not split)
    expect(result.sections).toHaveLength(6)
    expect(result.sections[0].heading).toContain('Patient summary')
    // The code block content should remain in section 0
    expect(result.sections[0].content).toContain(
      'This heading should not cause a split'
    )
  })

  it('preserves section content for sections without visuals', () => {
    const result = parseReport(DOCTOR_REPORT, 'doctor')
    // Patient summary should have the descriptive text
    expect(result.sections[0].content).toContain('SaaS product stuck')
    // Diagnosis should have the bold statement
    expect(result.sections[1].content).toContain('lack of clear product scope')
  })

  it('handles report with only title and no sections', () => {
    const titleOnly = `# Just a Title

**Some metadata**

---

_CTA with calendly link_`

    const result = parseReport(titleOnly, 'doctor')
    expect(result.title).toContain('Just a Title')
    expect(result.sections).toHaveLength(0)
    expect(result.ctaFooter).toContain('calendly')
  })

  it('detects all four risk levels', () => {
    const riskLevels = ['Low', 'Medium', 'High', 'Critical'] as const
    const expectedLevels = ['low', 'medium', 'high', 'critical'] as const

    for (let i = 0; i < riskLevels.length; i++) {
      const report = `# Report

**Generated by Test**

---

## Patient summary

Content.

## Diagnosis

Content.

## Symptoms vs. root cause

| A | B |
| --- | --- |
| x | y |

## Risk level

${riskLevels[i]}

Some elaboration on the risk.

## Recommended actions

1. **First** — A.
2. **Second** — B.

## What the AI can't see

Content.

---

_CTA with calendly_`

      const result = parseReport(report, 'doctor')
      expect(result.sections[3].visual).not.toBeNull()
      expect(result.sections[3].visual!.type).toBe('risk-gauge')
      const data = result.sections[3].visual!.data as { level: string }
      expect(data.level).toBe(expectedLevels[i])
    }
  })

  it('detects priority-roadmap with period inside bold (no dash separator)', () => {
    const report = `# Review Brief

**Generated by Test**

---

## What I reviewed

Content.

## What works

Content.

## What doesn't work

Content.

## The thing nobody's telling you

Content.

## If I had to prioritize

1. **Validate demand before touching code.** Run 5 manual orders this month.
2. **Solve the print dependency now.** Research Gelato and Printful.
3. **Define your visual style.** Pick a style, test it with 10 people.

## Where this review stops

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(report, 'critic')
    const section4 = result.sections[4]
    expect(section4.visual).not.toBeNull()
    expect(section4.visual!.type).toBe('priority-roadmap')

    const data = section4.visual!.data as {
      items: Array<{ label: string; fullText: string }>
    }
    expect(data.items).toHaveLength(3)
    expect(data.items[0].label).toBe('Validate demand before touching code')
    expect(data.items[0].fullText).toContain('Run 5 manual orders')
  })

  it('detects priority-roadmap with colon separator', () => {
    const report = `# Review Brief

**Generated by Test**

---

## What I reviewed

Content.

## What works

Content.

## What doesn't work

Content.

## The thing nobody's telling you

Content.

## If I had to prioritize

1. **Fix the GTM narrative:** Your go-to-market section needs work.
2. **Add customer validation:** Include concrete user quotes.

## Where this review stops

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(report, 'critic')
    const section4 = result.sections[4]
    expect(section4.visual).not.toBeNull()
    expect(section4.visual!.type).toBe('priority-roadmap')

    const data = section4.visual!.data as {
      items: Array<{ label: string; fullText: string }>
    }
    expect(data.items).toHaveLength(2)
    expect(data.items[0].label).toBe('Fix the GTM narrative')
  })

  it('detects priority-roadmap with no separator', () => {
    const report = `# Review Brief

**Generated by Test**

---

## What I reviewed

Content.

## What works

Content.

## What doesn't work

Content.

## The thing nobody's telling you

Content.

## If I had to prioritize

1. **Fix the GTM narrative** Your go-to-market section needs work.
2. **Add customer validation** Include concrete user quotes.

## Where this review stops

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(report, 'critic')
    const section4 = result.sections[4]
    expect(section4.visual).not.toBeNull()
    expect(section4.visual!.type).toBe('priority-roadmap')

    const data = section4.visual!.data as {
      items: Array<{ label: string; fullText: string }>
    }
    expect(data.items).toHaveLength(2)
    expect(data.items[0].label).toBe('Fix the GTM narrative')
  })

  it('strips numbered list items regardless of separator variant', () => {
    const report = `# Review Brief

**Generated by Test**

---

## What I reviewed

Content.

## What works

Content.

## What doesn't work

Content.

## The thing nobody's telling you

Content.

## If I had to prioritize

1. **Label one.** Description one.
2. **Label two:** Description two.
3. **Label three** — Description three.

## Where this review stops

Content.

---

_Full Stack Human — [Book a call →](https://calendly.com/fullstackhuman)_`

    const result = parseReport(report, 'critic')
    const section4 = result.sections[4]
    expect(section4.visual).not.toBeNull()
    // All numbered items should be stripped from content
    expect(section4.content).not.toContain('1.')
    expect(section4.content).not.toContain('2.')
    expect(section4.content).not.toContain('3.')
  })

  it('priority roadmap requires at least 2 items', () => {
    const report = `# Report

**Generated by Test**

---

## Patient summary

Content.

## Diagnosis

Content.

## Symptoms vs. root cause

| A | B |
| --- | --- |
| x | y |

## Risk level

High

## Recommended actions

1. **Only one item** — Not enough for a roadmap.

## What the AI can't see

Content.

---

_CTA with calendly_`

    const result = parseReport(report, 'doctor')
    // Only 1 item -> priority-roadmap should be null
    expect(result.sections[4].visual).toBeNull()
  })
})
