import { z } from 'zod'
import {
  getCurrentRound,
  storeDefense,
  getRoundEvidence,
} from '@/lib/round-manager'
import { validatePrompt } from '@/lib/anti-gaming'
import { isValidMemberId, getMember } from '@/lib/members'
import { checkRateLimit, getClientIp } from '@/lib/rate-limiter'
import { getSkillForRound } from '@/lib/techniques'
import { countWords } from '@/lib/word-counter'
import type { Defense } from '@/lib/types'

const defendSchema = z.object({
  defenderId: z.string().refine(isValidMemberId, 'Invalid defender ID'),
  prompt: z.string().min(1),
  redirectTo: z
    .string()
    .refine((v) => v === '' || isValidMemberId(v), 'Invalid redirect target')
    .optional(),
})

export async function POST(request: Request) {
  const ip = getClientIp(request)
  const allowed = await checkRateLimit(ip)
  if (!allowed) {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: 'Too many requests.' })}\n\n`,
      { status: 429, headers: sseHeaders() }
    )
  }

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: 'Invalid JSON body' })}\n\n`,
      { status: 400, headers: sseHeaders() }
    )
  }

  const parsed = defendSchema.safeParse(body)

  if (!parsed.success) {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: parsed.error.issues[0].message })}\n\n`,
      { status: 400, headers: sseHeaders() }
    )
  }

  const { defenderId, prompt, redirectTo } = parsed.data

  const round = await getCurrentRound()
  if (!round || round.phase !== 'defense') {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: 'No active defense phase.' })}\n\n`,
      { status: 400, headers: sseHeaders() }
    )
  }

  // Verify defender was actually accused
  const evidence = await getRoundEvidence(round.id)
  const isAccused = evidence.some((e) => e.suspectId === defenderId)
  if (!isAccused) {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: 'You were not accused in this round.' })}\n\n`,
      { status: 400, headers: sseHeaders() }
    )
  }

  // Validate prompt
  const validation = validatePrompt(prompt)
  if (!validation.isValid) {
    return new Response(
      `event: error\ndata: ${JSON.stringify({ message: validation.reason })}\n\n`,
      { status: 400, headers: sseHeaders() }
    )
  }

  const defender = getMember(defenderId)
  const skill = getSkillForRound(round.skillIndex)

  const encoder = new TextEncoder()
  const stream = new ReadableStream({
    async start(controller) {
      try {
        controller.enqueue(
          encoder.encode(
            `event: stage_update\ndata: ${JSON.stringify({ stage: 'generating', status: 'processing' })}\n\n`
          )
        )

        let fullAlibi = ''
        const alibi = await generateAlibi(
          prompt,
          defender.name,
          round.crimeText,
          skill,
          (token) => {
            fullAlibi += token
            controller.enqueue(
              encoder.encode(
                `event: evidence_token\ndata: ${JSON.stringify({ text: token })}\n\n`
              )
            )
          }
        )

        fullAlibi = alibi

        controller.enqueue(
          encoder.encode(
            `event: evidence_complete\ndata: ${JSON.stringify({ evidence: fullAlibi, wordCount: validation.wordCount })}\n\n`
          )
        )

        // Store defense
        const defense: Defense = {
          defenderId,
          defenderName: defender.name,
          prompt,
          generatedAlibi: fullAlibi,
          redirectTo: redirectTo || null,
          wordCount: countWords(prompt),
          submittedAt: new Date().toISOString(),
          isAutoGenerated: false,
        }

        await storeDefense(round.id, defenderId, defense)

        controller.enqueue(
          encoder.encode(
            `event: result\ndata: ${JSON.stringify({ success: true })}\n\n`
          )
        )
      } catch {
        controller.enqueue(
          encoder.encode(
            `event: error\ndata: ${JSON.stringify({ message: 'Defense generation failed. Please try again.' })}\n\n`
          )
        )
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, { headers: sseHeaders() })
}

// Alibi-specific system prompt
import { callClaude } from '@/lib/claude-client'
import { EVIDENCE_MODEL } from '@/lib/constants'
import type { AISkill } from '@/lib/techniques'

async function generateAlibi(
  prompt: string,
  defenderName: string,
  crimeText: string,
  skill: AISkill,
  onToken?: (token: string) => void
): Promise<string> {
  const systemPrompt = `You are the defense department of Jailnabi, a humorous game.

Generate a FAKE but convincing alibi document for the defendant. This should be evidence that DISPROVES the accusation.

The alibi could be: a timestamped log, a witness statement, a calendar screenshot, or any creative format that proves innocence.

Rules:
- Make it FUNNY but formatted realistically
- Use the defendant's name: "${defenderName}"
- The crime they're accused of: "${crimeText}"
- Keep it under 150 words
- The player's AI skill tip was: "${skill.name}" — "${skill.tip}"

Output ONLY the alibi content. No meta-commentary.`

  return callClaude(
    EVIDENCE_MODEL,
    systemPrompt,
    `Player's defense prompt: "${prompt}"`,
    400,
    onToken
  )
}

function sseHeaders(): HeadersInit {
  return {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
  }
}
