// ─── Types (inline — no @/* imports) ───

interface SeedMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  isReport: boolean
  timestamp: number
}

interface SeedConversation {
  persona: 'doctor' | 'critic' | 'guide'
  status: 'active' | 'completed' | 'abandoned'
  messages: SeedMessage[]
  report?: {
    content: string
    isBranded: boolean
  }
}

// ─── Helpers ───

let msgCounter = 0
const BASE_TS = Date.now() - 9 * 3_600_000 // offset conversations in time

function msg(
  role: 'user' | 'assistant',
  content: string,
  isReport = false
): SeedMessage {
  msgCounter++
  return {
    id: `seed-${msgCounter.toString().padStart(4, '0')}`,
    role,
    content,
    isReport,
    timestamp: BASE_TS + msgCounter * 60_000,
  }
}

function resetMsgCounter(conversationIndex: number) {
  msgCounter = conversationIndex * 100
}

// ─── Report Content ───

const DOCTOR_REPORT_1_CRITICAL = `Alright. Let me write this up.

---

# \u{1FA7A} Project Diagnostic Report

**Generated by FullStackHuman AI — The Doctor**
**Date:** February 23, 2026

---

## Patient summary

E-commerce platform for luxury fashion brands. 18 months in development, team of 8, burning $120K/month. Launch delayed 3 times. CEO brought in a new CTO 4 months ago to "fix things" — since then, the codebase has been in a rewrite cycle while the original team bleeds morale and customers wait.

## Diagnosis

**You have two codebases, zero shipped products, and a leadership layer that is solving the wrong problem.**

The new CTO diagnosed the original code as "not scalable" and initiated a ground-up rewrite. This created a second codebase that is architecturally cleaner but functionally incomplete. Meanwhile, the original codebase — which was 80% feature-complete — stopped receiving investment. You now have two half-built systems and a team split between maintaining the old and building the new.

## Symptoms vs. root cause

| What it looks like | What's actually happening |
|---|---|
| "We keep delaying launch" | There is no launchable product — the rewrite reset the clock to zero |
| "The team is frustrated" | Engineers are maintaining code they've been told is being replaced |
| "The new CTO says we need 6 more months" | The rewrite is being scoped as a greenfield project, not a migration |
| "Customers are losing patience" | Promises were made based on the original timeline, which no longer exists |
| "We can't hire fast enough" | New hires are onboarding into a moving target with no stable architecture |

## Risk level

**Critical**

You are burning runway on a rewrite that hasn't shipped a single feature to production. At $120K/month and a 6-month projected timeline, you're committing $720K to an unvalidated architecture bet. If the rewrite hits its own complexity wall — and rewrites almost always do — you'll have spent your runway on two unshippable codebases.

## Recommended actions

1. **Stop the rewrite immediately** — Declare a 2-week freeze on new architecture work. This is not about abandoning the rewrite permanently — it's about stopping the bleeding long enough to make a real decision.

2. **Audit the original codebase honestly** — The original code was 80% done. Before the CTO arrived, what was actually blocking launch? Get specific: is it performance, features, or quality? Most "unscalable" code can ship to 1,000 users just fine.

3. **Define a minimum viable launch from what exists** — Take the original codebase, strip it to the 3 features that matter most to your first 50 customers, and define a 6-week sprint to ship those. This gives you revenue, validation, and breathing room.

4. **Align the CTO on an incremental migration strategy** — If the new architecture is genuinely better, migrate module by module after launch. Strangler fig pattern. The rewrite-from-scratch approach is how you burn through your runway with nothing to show.

5. **Have the hard conversation with your board** — They need to know the launch timeline reset. Hiding it makes the eventual reveal worse. Come with the new plan, not just the bad news.

\`\`\`action-matrix
{"actions":[{"label":"Stop the rewrite","impact":10,"urgency":10,"index":1},{"label":"Audit original code","impact":8,"urgency":9,"index":2},{"label":"Define MVP launch","impact":9,"urgency":8,"index":3},{"label":"Incremental migration","impact":7,"urgency":5,"index":4},{"label":"Board conversation","impact":6,"urgency":7,"index":5}]}
\`\`\`

## What the AI can't see

- The actual quality of both codebases — "not scalable" is subjective and often means "not how I would build it"
- The interpersonal dynamic between the original lead dev and the new CTO — this is often the real blocker
- Whether the board has the appetite for another 6 weeks or if they're already looking for the exit
- The real François would spend a day with both the CTO and the original team lead separately, then bring them into a room together with a whiteboard and a migration plan — because the technical decision is actually a people decision

---

_FullStackHuman — The real François has navigated exactly this kind of CTO transition gone wrong. He'd facilitate the hard conversations between your old and new technical leadership, audit both codebases honestly, and help you build a launch plan that doesn't require picking a winner. [Book a call →](https://fullstackhuman.sh/book)_`

const DOCTOR_REPORT_2_HIGH = `Let me put this together for you.

---

# \u{1FA7A} Project Diagnostic Report

**Generated by FullStackHuman AI — The Doctor**
**Date:** February 23, 2026

---

## Patient summary

B2B SaaS for construction project management. 20 paying customers, 2 devs, CEO/PM wearing multiple hats. Shipped fast for 6 months, then hit a wall after a trade show flooded the backlog with requests. Nothing ships cleanly anymore — 6 things in flight, constant reprioritization, devs context-switching on the CEO's latest conversation.

## Diagnosis

**You are the bottleneck — not because you're incompetent, but because you've become a single, unfiltered pipeline between customer noise and dev execution.**

Every customer interaction you have goes directly into the work queue with no processing layer between "I heard this" and "build this." At 5 customers that was fine — the signal was clear, the scope was small. At 20 customers after a trade show, it's created a system where nothing has stable priority long enough to get finished.

## Symptoms vs. root cause

| What it looks like | What's actually happening |
|---|---|
| "Features take forever to ship" | Devs are restarting work mid-cycle — nothing is actually slow, it's never truly started |
| "We're juggling 6 things at once" | You have no WIP limit — everything is in progress, nothing is done |
| "I keep reprioritizing based on who I talked to last" | Customer input has no processing layer — you're using recency as a proxy for importance |
| "Every request feels urgent" | Without a prioritization framework, urgency is determined by emotion, not business impact |
| "We need a third dev" | Adding capacity to a broken flow just creates a third person thrashing |

## Risk level

**High**

If nothing changes in the next 30 days, you risk burning out your two devs — good engineers leave when they can't see their own progress. You also risk churning customers who were promised features that never land. At 20 customers, one or two churn stories can poison your sales conversations.

## Recommended actions

1. **Freeze the queue today** — Pick the 2-3 things closest to done and finish them before anything new starts. Declare a "no new starts" rule until those ship.

2. **Install a weekly prioritization ritual** — Once a week, you set the priority for the next 7 days. Customer conversations get captured but don't change the plan until the next review.

3. **Define your WIP limit** — Two devs means a maximum of 2 things in active development. One feature per dev. Never start a third.

4. **Create a simple intake filter** — Before anything goes on the list: Does this affect more than one customer? Does the churn risk justify the cost? Can we ship something smaller?

5. **Have an honest conversation with your devs** — They already know something is broken. Naming it together resets the contract.

\`\`\`action-matrix
{"actions":[{"label":"Freeze the queue","impact":8,"urgency":10,"index":1},{"label":"Weekly prioritization","impact":9,"urgency":8,"index":2},{"label":"Set WIP limit","impact":9,"urgency":7,"index":3},{"label":"Intake filter","impact":7,"urgency":6,"index":4},{"label":"Talk to your devs","impact":8,"urgency":8,"index":5}]}
\`\`\`

## What the AI can't see

- How mature your devs are — WIP limits work differently with seniors vs juniors
- The actual state of those 6 in-flight features — some might be zombies that should be killed
- Whether there's a tech debt layer compounding the process problem
- The real François would spend a half-day mapping your backlog, killing the zombies, and coaching you on holding the line with customers

---

_FullStackHuman — The real François specializes in exactly this inflection point: when a scrappy early team needs just enough structure to stop thrashing without losing speed. He'd work directly with you and your devs to install a lightweight delivery system that fits your context. [Book a call →](https://fullstackhuman.sh/book)_`

const DOCTOR_REPORT_3_MEDIUM = `Here's what I see.

---

# \u{1FA7A} Project Diagnostic Report

**Generated by FullStackHuman AI — The Doctor**
**Date:** February 23, 2026

---

## Patient summary

Consumer mobile app for fitness tracking with social features. 8,000 MAU, retention dropping from 40% to 22% over 3 months. Team of 4 devs plus a designer. The founder suspects the onboarding flow is the problem, but users who complete onboarding are also churning.

## Diagnosis

**Your retention problem isn't onboarding — it's the gap between what users sign up for and what they experience in week 2.**

The first session is polished. The social features are marketed heavily. But the social graph is empty for new users — they land in a feed with no friends, no activity, and no reason to come back. The product sells a social experience and delivers a solo one.

## Symptoms vs. root cause

| What it looks like | What's actually happening |
|---|---|
| "Retention is dropping" | Users complete onboarding but find an empty social feed on day 2 |
| "Onboarding must be broken" | Onboarding converts fine — the problem is what comes after |
| "Users aren't inviting friends" | The invite flow is buried 3 taps deep and offers no incentive |
| "Feature requests keep coming" | Users are asking for things to do alone because the social promise failed |

## Risk level

**Medium**

You have 8,000 MAU and a working core product. The retention decline is real but reversible if you address the empty-room problem within the next 6-8 weeks. The risk becomes high if you spend those weeks building new features instead of fixing the core loop.

## Recommended actions

1. **Seed the social experience for new users** — Create curated content, staff accounts, or community challenges that give new users something to engage with before their friends join. The cold start problem is solved by manufacturing warmth.

2. **Surface the invite flow in the first session** — Move friend invites from a settings submenu to the post-workout celebration screen. "Share your first workout" is a natural moment.

3. **Add an async social hook** — Push notifications when a friend works out, weekly leaderboards, or streak comparisons. Give users a reason to open the app that isn't their own motivation.

4. **Instrument the day 2-7 experience** — You're measuring onboarding completion and monthly retention. You need to see what happens on day 2, day 4, day 7. That's where the story is.

## What the AI can't see

- Whether the social features actually work well when users have friends — maybe the social experience is also broken
- Your analytics setup — I'm guessing at the instrumentation gaps
- How much design debt exists in the invite flow
- The real François would run a cohort analysis with you, map the actual user journey hour by hour for the first week, and design the social hooks based on real behavioral data

---

_FullStackHuman — The real François has built social products from zero. He'd dig into your analytics, map the day-by-day drop-off, and design the minimum viable social loop that turns solo users into connected ones. [Book a call →](https://fullstackhuman.sh/book)_`

const DOCTOR_REPORT_4_LOW = `Here's my read on this.

---

# \u{1FA7A} Project Diagnostic Report

**Generated by FullStackHuman AI — The Doctor**
**Date:** February 23, 2026

---

## Patient summary

Internal project management tool used by a 50-person consulting firm. Built 4 years ago by a contractor, currently maintained by one part-time dev. Works fine but looks dated, runs on an older framework, and new hires keep asking why they can't use Notion instead.

## Diagnosis

**Your tool isn't broken — it's losing the internal marketing war to consumer-grade alternatives.**

The functionality works. The data is there. But the UI feels 2019, and every new hire who's used Notion or Linear walks in with higher expectations. The real risk isn't technical — it's adoption erosion as people quietly start using shadow tools.

## Symptoms vs. root cause

| What it looks like | What's actually happening |
|---|---|
| "The tool looks outdated" | The UI hasn't been refreshed since launch — it works but doesn't feel modern |
| "New hires want to use Notion" | Consumer tool expectations have outpaced your internal tool's UX |
| "We should probably rewrite it" | A UI refresh would solve 80% of the perception problem at 20% of the cost |
| "The contractor's code is messy" | The code is stable and works — "messy" often means "unfamiliar to the current maintainer" |

## Risk level

**Low**

The tool works, the data is intact, and adoption is still at 70%+. You have time to modernize incrementally. The risk only escalates if you ignore the shadow tooling trend for another 6 months — at that point, data fragmentation becomes a real problem.

## Recommended actions

1. **Refresh the UI, not the architecture** — A modern CSS framework, updated components, and a cleaner layout would transform perception without touching business logic. Budget 4-6 weeks of part-time dev work.

2. **Run a 30-minute user interview with 5 employees** — Ask what they actually use the tool for, where they get frustrated, and what they're doing in Notion instead. The answers will surprise you and focus the refresh.

3. **Add the top 3 quality-of-life features** — Based on the interviews, pick the 3 small things that would make daily use feel better. Usually it's search, keyboard shortcuts, and faster loading.

\`\`\`action-matrix
{"actions":[{"label":"UI refresh","impact":8,"urgency":5,"index":1},{"label":"User interviews","impact":7,"urgency":6,"index":2},{"label":"QoL features","impact":6,"urgency":4,"index":3}]}
\`\`\`

## What the AI can't see

- How deeply Notion has already penetrated your workflows — if critical project data is already there, the migration calculus changes
- The actual state of the codebase — "old framework" could mean anything from jQuery to Angular 8
- Whether the part-time dev has the design chops for a UI refresh or if you need a designer
- The real François would audit the current tool, interview a cross-section of users, and deliver a prioritized modernization roadmap that respects your budget constraints

---

_FullStackHuman — The real François has modernized legacy internal tools for companies your size. He'd assess what you actually need, separate the cosmetic from the structural, and give you a plan that a part-time dev can execute. [Book a call →](https://fullstackhuman.sh/book)_`

const CRITIC_REPORT_5 = `Here's my honest assessment.

---

# \u{1F50D} Review Brief

**Generated by FullStackHuman AI — The Critic**
**Date:** February 23, 2026

---

## What I reviewed

A Series A pitch deck for an HR-tech startup building AI-powered employee engagement analytics. 18 slides, targeting $4M raise. The deck covers market size, product demo, team, financials, and go-to-market.

\`\`\`assessment-radar
{"dimensions":[{"name":"Value Proposition","score":7},{"name":"Market Analysis","score":5},{"name":"Product Depth","score":8},{"name":"Go-to-Market","score":3},{"name":"Team Story","score":6},{"name":"Financial Model","score":4}]}
\`\`\`

## What works

- **The product demo slides are genuinely compelling.** The before/after comparison of an HR dashboard vs. your analytics view makes the value immediately tangible. This is your strongest section — lead with it in meetings.

- **The problem statement resonates.** "HR teams are drowning in survey data but starving for insights" is a clean framing that any HR leader would nod at. You've earned the right to propose a solution.

- **Technical differentiation is clear.** The NLP pipeline explanation is accessible without being dumbed down. Investors will understand why this isn't just another dashboard.

## What doesn't work

- **The market size slide is hand-wavy.** You cite "$14B HR tech market" with no source and no clear logic for how you get to your SAM. Investors have seen this slide a thousand times — you need bottom-up math, not top-down TAM.

- **The go-to-market section is one slide with three bullet points.** This is the weakest part of the deck. You say "enterprise sales" but show no proof you can sell to enterprises — no pipeline, no LOIs, no named design partners. At Series A, this is what investors are actually funding: proof you can sell, not just build.

- **The financial model assumes 40% month-over-month growth for 24 months straight.** That's not a model, it's a wish. Replace it with a bottoms-up projection based on your current pipeline and conversion rates.

## The thing nobody's telling you

Your biggest risk isn't the product. It's that you're positioned as an enterprise play with a founder-led sales motion and zero enterprise sales infrastructure. The investors you're targeting know that enterprise HR tech has 6-12 month sales cycles, and nothing in your deck shows you've internalized that timeline. You're showing a product that's ready and a business that isn't.

The deck reads like it was written by the technical co-founder. That's fine for a seed round. At Series A, investors want to see that someone on the team understands the commercial machine as well as the technical one.

## If I had to prioritize

1. **Rebuild the GTM section from scratch** — Show your current pipeline, name your design partners, and explain your sales process step by step. If you don't have this, that's the real problem to solve before you raise.

2. **Replace the TAM slide with bottom-up math** — Start with "there are X companies with Y+ employees in our target verticals" and work up from unit economics. It's more credible and shows you understand your market.

3. **Add a slide on sales cycle and proof points** — Investor objection #1 will be "can you actually sell this?" Preempt it with a slide showing your funnel, average deal size, and time-to-close from your existing customers.

4. **Cut the financial projections to one realistic scenario** — Show 18 months based on current trajectory with clear assumptions. Add a "with Series A investment" scenario that shows what the money buys in terms of sales headcount and pipeline.

## Where this review stops

- I haven't assessed the competitive landscape section — you didn't include one, which is itself a finding
- I can't evaluate the technical claims about your NLP accuracy without seeing the product
- The cap table and terms aren't in scope here
- The real François would do a mock pitch session with you, play the skeptical investor, and help you rebuild the GTM narrative with real pipeline data

---

_FullStackHuman — The real François has reviewed hundreds of pitch decks and sat on both sides of the table. He'd run a mock pitch with you, pressure-test every claim, and help you rebuild the weak sections with data investors actually want to see. [Book a call →](https://fullstackhuman.sh/book)_`

const GUIDE_REPORT_6_FRAMEWORK_MATRIX = `Let me give you a framework for this.

---

# \u{1F9ED} Framework Brief

**Generated by FullStackHuman AI — The Guide**
**Date:** February 23, 2026

---

## What you asked

Should we build a custom customer data platform or buy an existing solution like Segment or RudderStack? We're a 30-person e-commerce company doing $8M ARR with a growing data team.

## How to think about this

The build-vs-buy question is never purely technical. It's a question about where your competitive advantage lives and whether you have the organizational capacity to maintain what you build.

\`\`\`framework-matrix
{"title":"Build vs Buy Decision Matrix","xAxisLabel":"Differentiation","xAxisLow":"Commodity need","xAxisHigh":"Core differentiator","yAxisLabel":"Internal Capability","yAxisLow":"Weak or absent","yAxisHigh":"Strong and proven","quadrants":{"topLeft":{"label":"Build trap","description":"You can build it but it won't matter"},"topRight":{"label":"Build here","description":"Core advantage with team to execute"},"bottomLeft":{"label":"Buy now","description":"Commodity need, no team to build"},"bottomRight":{"label":"Partner or hire","description":"Core need but no capability yet"}},"userPosition":{"x":0.35,"y":0.45}}
\`\`\`

Based on what you've described, you're sitting in the space between "buy now" and "build trap." Your data needs are real but not yet differentiated — you want the same things every e-commerce company wants from a CDP. And your data team is growing but not yet proven on infrastructure projects.

## The reframe

You're not really asking "build or buy." You're asking "where should my data team spend its time?" And the answer is: on the things that make your customer experience different from every other e-commerce company — not on plumbing.

## Applied to your situation

Buy a CDP now. Use the time your data team would have spent building infrastructure to instead build the analytics and personalization models that sit on top of it. In 18 months, if your data volume and use cases outgrow the vendor, you'll have a team that understands the problem deeply enough to build the right thing — not the thing they imagine today.

The most common regret in build-vs-buy isn't buying when you should have built. It's building too early, before you understood the problem well enough.

## What to sit with

- If you build this and it takes 6 months, what doesn't get built during that time? Is that trade-off worth it?
- Is your data team excited about building infrastructure, or about building models? Those are different people with different motivations.

## Where this goes deeper

- How to evaluate CDP vendors for your specific use case and data volume
- Building a data team roadmap that separates infrastructure from insight work
- The migration path from a vendor CDP to a custom solution if you outgrow it
- The real François would sit with your data team lead, map your actual data flows, and help you write a vendor evaluation that tests the things that will matter at 3x your current scale

---

_FullStackHuman — The real François has guided multiple companies through this exact decision. He'd help you evaluate vendors against your actual data architecture, negotiate the right contract terms, and design the long-term data strategy that keeps your options open. [Book a call →](https://fullstackhuman.sh/book)_`

const GUIDE_REPORT_7_CONCEPT_SPECTRUM = `Here's a way to think about this.

---

# \u{1F9ED} Framework Brief

**Generated by FullStackHuman AI — The Guide**
**Date:** February 23, 2026

---

## What you asked

How should we think about technical debt? Our codebase is 3 years old, some parts are messy, and the team keeps asking for a "cleanup sprint." I'm not sure if that's the right move or a waste of time.

## How to think about this

Most teams treat technical debt as a binary: either you ignore it or you stop everything and clean it up. Neither works. The useful frame is a spectrum of strategies, and the right position depends on your business context, not your code quality.

\`\`\`concept-spectrum
{"title":"Technical Debt Strategy","leftLabel":"Big rewrite","rightLabel":"Ignore forever","userPosition":0.35,"userLabel":"Selective cleanup","midLabel":"Continuous refactor"}
\`\`\`

You're describing a team that wants to move toward the left — a dedicated cleanup effort. But based on your situation (3-year codebase, still shipping features, team not blocked), the right position is closer to center: continuous, targeted refactoring woven into feature work.

## The reframe

Technical debt isn't a problem to solve. It's a cost to manage. The question isn't "should we clean up the code?" — it's "which specific debts are slowing us down right now, and which ones can we live with?"

A cleanup sprint feels productive but rarely is. It's the engineering equivalent of reorganizing your desk instead of doing the hard work. The messy parts of your code that nobody touches? They're not debt. They're paid off. The messy parts that you change every week? Those are the ones costing you.

## Applied to your situation

Instead of a cleanup sprint, try this: for the next 4 weeks, every feature PR must include one refactoring task in the area it touches. The team improves the code they're actively working in, and the parts nobody touches stay untouched. After 4 weeks, assess whether velocity improved. If it did, make it permanent. If it didn't, the debt wasn't actually the problem.

## What to sit with

- If you gave the team a full cleanup sprint and they finished it, would they ship faster afterward? Or would they just find new things to clean?
- What if the messiness isn't a technical problem but a documentation problem — would better onboarding docs solve the same frustration cheaper?

## Where this goes deeper

- How to quantify which technical debts actually cost you velocity
- The difference between accidental debt (we didn't know better) and deliberate debt (we chose speed) — they require different strategies
- Building a culture where refactoring is continuous, not event-driven
- The real François would review your codebase with the team, identify the 3-5 areas where debt is actually slowing you down, and build a pay-down plan integrated into your sprint cycles

---

_FullStackHuman — The real François has helped engineering teams at every stage build sustainable code quality practices. He'd assess your actual codebase, separate the cosmetic debt from the costly debt, and design a pragmatic pay-down strategy your team will actually follow. [Book a call →](https://fullstackhuman.sh/book)_`

// ─── Conversations ───

export const SEED_CONVERSATIONS: SeedConversation[] = [
  // ─── 1. Doctor — Critical risk — action-matrix ───
  (() => {
    resetMsgCounter(0)
    return {
      persona: 'doctor' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Alright, let's figure out what's going on. No judgment — every project gets stuck. The question is *why*.\n\nTell me what you're building and where it hurts."
        ),
        msg(
          'user',
          "We're building an e-commerce platform for luxury fashion brands. Custom storefronts, inventory management, the whole thing. We've been at it for 18 months with 8 engineers. We were supposed to launch last quarter but we've delayed 3 times now. 4 months ago the board brought in a new CTO who decided the original codebase wasn't scalable enough and started a rewrite. Now we have two half-built systems and nothing to show customers."
        ),
        msg(
          'assistant',
          'That\'s a pattern I\'ve seen before, and it rarely ends well without intervention.\n\nTwo questions:\n\n1. How far along was the original codebase when the new CTO arrived? Could it have launched — even imperfectly — to a small set of customers?\n2. What specifically did the CTO flag as "not scalable"? Was there a technical assessment, or was it more of a gut call?'
        ),
        msg(
          'user',
          "The original was probably 80% feature-complete. One of the original devs told me they could have launched to our first 3 pilot brands with a month of polish. The CTO came in, spent two weeks reviewing the code, and said it was built on patterns that wouldn't scale past 50 brands. He wanted to move to a microservices architecture. There wasn't a formal assessment — it was more his experience from his last company."
        ),
        msg(
          'assistant',
          "Got it. So an 80%-done monolith that could have launched, replaced by a microservices rewrite based on one person's architectural preference rather than measured bottlenecks.\n\nHere's what I think happened: the new CTO optimized for the company you might be in 3 years instead of the company you are today. Microservices at 0 customers is architecture astronautics — you don't have the traffic, the team size, or the operational maturity to justify the complexity.\n\nDoes that track with what you're seeing?"
        ),
        msg(
          'user',
          "Yeah, that's exactly it. The board is asking why we haven't launched and I don't know what to tell them."
        ),
        msg('assistant', DOCTOR_REPORT_1_CRITICAL, true),
      ],
      report: {
        content: DOCTOR_REPORT_1_CRITICAL,
        isBranded: true,
      },
    }
  })(),

  // ─── 2. Doctor — High risk — action-matrix ───
  (() => {
    resetMsgCounter(1)
    return {
      persona: 'doctor' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Alright, let's figure out what's going on. No judgment — every project gets stuck. The question is *why*.\n\nTell me what you're building and where it hurts."
        ),
        msg(
          'user',
          "We're a B2B SaaS doing project management for construction companies. 20 paying customers, 2 devs, me as CEO/PM. We shipped fast for 6 months but now everything takes forever. Features keep getting started but nothing ships. I think we need to hire a third dev but I'm not sure that's the real problem."
        ),
        msg(
          'assistant',
          'Good instinct to question the hire. "Everything takes forever" with two devs who shipped fast for six months — that\'s a pattern shift, not a capacity problem. Something changed.\n\nTwo questions:\n\n1. What does your current delivery process look like? How does a feature go from idea to shipped?\n2. What was the last thing that shipped cleanly? And what changed after that?'
        ),
        msg(
          'user',
          "Process is... informal. I talk to customers, figure out what they need, write up a quick brief in Notion, and the devs pick it up. No sprints or anything — we just have a running list and they grab what's next. It worked great when we had 5 customers and a clear roadmap.\n\nThe last thing that shipped cleanly was our reporting dashboard, maybe 3 months ago. After that I came back from a construction trade show with a ton of feature requests from prospects and existing customers. Since then we've been juggling like 6 things at once. The devs keep context-switching because I keep reprioritizing based on whoever I talked to last. I know that's probably part of it but I don't know how else to handle it."
        ),
        msg(
          'assistant',
          "That's enough. You just diagnosed yourself in the last sentence — and I want to make sure you heard it.\n\nHere's what I think is actually happening: **you don't have a delivery problem, you have a prioritization bottleneck.** The devs aren't slow. They're thrashing. Every context switch costs them 30-60 minutes of re-entry time, and you're triggering those switches multiple times a week.\n\nThe third dev wouldn't fix this. They'd just be a third person thrashing.\n\nDoes that land, or am I missing something?"
        ),
        msg('user', 'You got it right.'),
        msg('assistant', DOCTOR_REPORT_2_HIGH, true),
      ],
      report: {
        content: DOCTOR_REPORT_2_HIGH,
        isBranded: true,
      },
    }
  })(),

  // ─── 3. Doctor — Medium risk — priority-roadmap (no action-matrix) ───
  (() => {
    resetMsgCounter(2)
    return {
      persona: 'doctor' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Alright, let's figure out what's going on. No judgment — every project gets stuck. The question is *why*.\n\nTell me what you're building and where it hurts."
        ),
        msg(
          'user',
          "We have a fitness app with about 8,000 monthly active users. Retention has dropped from 40% to 22% in three months and we can't figure out why. Our onboarding flow has good completion rates so I don't think that's it. We have social features but they don't seem to be driving engagement like we hoped."
        ),
        msg(
          'assistant',
          "Interesting. Onboarding completes fine but retention drops — that tells me the problem is in what happens *after* onboarding, not during it.\n\nTwo things I want to understand:\n\n1. When you say social features — what does a new user's social feed look like on day 2? Are they seeing activity from friends, or is it empty?\n2. How are users currently discovering and inviting friends?"
        ),
        msg(
          'user',
          "Honestly, a new user's feed is pretty empty on day 2. They sign up, do a workout, and then the next day the social feed has nothing unless they already had friends on the platform. The invite flow is in the settings menu — you have to tap through profile, settings, then invite friends. We know it's buried but we haven't had time to fix it because we've been building new features."
        ),
        msg(
          'assistant',
          "There it is. You're selling a social fitness experience and delivering a solo one. The onboarding is fine — users *want* the social experience. They just can't find it.\n\nEmpty social feeds on day 2 are a classic cold start problem. And burying the invite flow 3 taps deep means the one mechanism that could fix the empty feed is invisible.\n\nYour team has been building new features to compensate for the one feature that's broken: the social loop itself.\n\nMake sense?"
        ),
        msg(
          'user',
          "That makes a lot of sense. We've been treating the symptoms."
        ),
        msg('assistant', DOCTOR_REPORT_3_MEDIUM, true),
      ],
      report: {
        content: DOCTOR_REPORT_3_MEDIUM,
        isBranded: true,
      },
    }
  })(),

  // ─── 4. Doctor — Low risk — action-matrix ───
  (() => {
    resetMsgCounter(3)
    return {
      persona: 'doctor' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Alright, let's figure out what's going on. No judgment — every project gets stuck. The question is *why*.\n\nTell me what you're building and where it hurts."
        ),
        msg(
          'user',
          "It's not really stuck — more like aging. We have an internal project management tool that our 50-person consulting firm uses. It was built 4 years ago by a contractor, one dev maintains it part-time. It works fine functionally but it looks dated and new hires keep asking why we don't just use Notion or Linear."
        ),
        msg(
          'assistant',
          "So the tool works, but it's losing the perception battle against modern consumer tools.\n\nTwo questions:\n\n1. What percentage of the team actively uses the tool daily vs. has quietly migrated parts of their workflow to other tools like Notion?\n2. Has anyone done a formal assessment of the codebase — do you know what framework it's on and whether a UI refresh is even feasible?"
        ),
        msg(
          'user',
          "I'd say about 70% use it daily. I know at least two project managers have started using Notion for their own planning and just copy the status updates into our tool. The codebase is React — I think an older version — with an Express backend. The part-time dev said it's messy but workable. No formal assessment."
        ),
        msg(
          'assistant',
          'That 70% number is actually healthy — you have time. The real signal is those two PMs using shadow tools. That\'s how adoption erosion starts: slowly, then all at once.\n\nBut the good news is this is a perception problem more than a technical one. React + Express is a perfectly modern stack. "Messy" usually means "unfamiliar to the current maintainer" — not "needs a rewrite."\n\nI think the fix is smaller than you expect. Want me to write this up?'
        ),
        msg('user', 'Yes please.'),
        msg('assistant', DOCTOR_REPORT_4_LOW, true),
      ],
      report: {
        content: DOCTOR_REPORT_4_LOW,
        isBranded: true,
      },
    }
  })(),

  // ─── 5. Critic — assessment-radar + priority-roadmap ───
  (() => {
    resetMsgCounter(4)
    return {
      persona: 'critic' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Alright, show me what you've got. I'll give you my honest take — what works, what doesn't, and the thing nobody's telling you.\n\nWhat are you submitting for review?"
        ),
        msg(
          'user',
          "I need a review of our Series A pitch deck. We're an HR-tech startup building AI-powered employee engagement analytics. We've got 18 slides and we're targeting a $4M raise. The deck covers our product, market size, team, financial projections, and go-to-market strategy. We've pitched to 3 VCs so far and got polite passes — no harsh feedback but no term sheets either."
        ),
        msg(
          'assistant',
          "Polite passes with no feedback usually means the deck isn't bad enough to critique openly but isn't compelling enough to act on. That's actually the hardest position to be in — you need someone to tell you what's actually wrong.\n\nTwo questions before I review:\n\n1. What's your current traction? Revenue, customers, pipeline — whatever you have.\n2. Who on the team is doing the pitching, and what's their background?"
        ),
        msg(
          'user',
          "We have 12 paying customers, $180K ARR, growing about 15% month over month. Pipeline has another 8 companies in various stages. I'm the CEO and technical co-founder — I do the pitching. My background is ML engineering, spent 6 years at a big tech company building NLP systems before starting this. My co-founder is our head of product, comes from HR tech."
        ),
        msg(
          'assistant',
          "Okay, $180K ARR at 15% MoM growth with 12 customers is actually solid traction for a Series A in HR-tech. The fact that you're getting polite passes tells me the traction isn't the problem — the deck is underselling you.\n\nLet me review this section by section."
        ),
        msg('user', 'Go ahead.'),
        msg('assistant', CRITIC_REPORT_5, true),
      ],
      report: {
        content: CRITIC_REPORT_5,
        isBranded: true,
      },
    }
  })(),

  // ─── 6. Guide — framework-matrix ───
  (() => {
    resetMsgCounter(5)
    return {
      persona: 'guide' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Interesting question. I won't give you a yes-or-no answer — that's not how this works.\n\nInstead, I'll give you a framework to think through it yourself, because the right answer depends on context only you have.\n\nWhat are you trying to figure out?"
        ),
        msg(
          'user',
          "We're debating whether to build a custom customer data platform or buy something like Segment or RudderStack. We're a 30-person e-commerce company doing $8M ARR. We have a growing data team — just hired our third data engineer — and the CEO wants to make data-driven personalization our competitive edge."
        ),
        msg(
          'assistant',
          'Good context. The CEO framing this as a competitive edge is important — it tells me the motivation is strategic, not just operational.\n\nBut there\'s a gap I want to probe: when you say "build a custom CDP," what does that actually mean to your team? Are they imagining building the data pipeline infrastructure, or building the models and personalization logic that sits on top of a pipeline?\n\nBecause those are very different projects with very different build-vs-buy answers.'
        ),
        msg(
          'user',
          'That\'s a good distinction. I think the data team is excited about building the whole thing — the pipelines, the event collection, the identity resolution. But honestly, what makes us different is the personalization models, not the plumbing. Our CEO just sees "data platform" and thinks competitive advantage.'
        ),
        msg(
          'assistant',
          'You just answered your own question. Let me give you a framework that makes this clearer.'
        ),
        msg('user', "I'd like that."),
        msg('assistant', GUIDE_REPORT_6_FRAMEWORK_MATRIX, true),
      ],
      report: {
        content: GUIDE_REPORT_6_FRAMEWORK_MATRIX,
        isBranded: true,
      },
    }
  })(),

  // ─── 7. Guide — concept-spectrum ───
  (() => {
    resetMsgCounter(6)
    return {
      persona: 'guide' as const,
      status: 'completed' as const,
      messages: [
        msg(
          'assistant',
          "Interesting question. I won't give you a yes-or-no answer — that's not how this works.\n\nInstead, I'll give you a framework to think through it yourself, because the right answer depends on context only you have.\n\nWhat are you trying to figure out?"
        ),
        msg(
          'user',
          "How should we think about technical debt? Our codebase is 3 years old, some parts are messy, and the team keeps asking for a 'cleanup sprint.' I'm not sure if that's the right move or a waste of time. We're still shipping features and nothing is broken — it's just getting harder to work in certain areas."
        ),
        msg(
          'assistant',
          "The fact that you're still shipping features is important context. A lot of teams treat technical debt like it's a crisis when it's really a cost of doing business.\n\nTwo questions:\n\n1. When the team says \"cleanup sprint,\" what specifically do they want to clean up? Is it scattered across the codebase, or concentrated in a few areas?\n2. How much of the codebase do you actually touch in a typical month? Because debt in code nobody changes is debt that's already paid off."
        ),
        msg(
          'user',
          "The complaints are concentrated — it's mainly the user authentication module and the payment processing integration. Those are the areas that get changed most often. The rest of the codebase is older but nobody really works in it. I'd say we actively modify maybe 30% of the code in any given month.\n\nThe team wants 2 weeks to just clean things up. No features, just refactoring."
        ),
        msg(
          'assistant',
          "So 70% of the code is stable and untouched, and the pain is in 2 specific modules that happen to be high-traffic areas for development.\n\nThat changes the equation significantly. You don't have a codebase-wide debt problem. You have two hot spots.\n\nLet me give you a framework that reframes this from an all-or-nothing decision to a strategic one."
        ),
        msg('user', 'Please do.'),
        msg('assistant', GUIDE_REPORT_7_CONCEPT_SPECTRUM, true),
      ],
      report: {
        content: GUIDE_REPORT_7_CONCEPT_SPECTRUM,
        isBranded: true,
      },
    }
  })(),

  // ─── 8. Doctor — active (mid-intake, no report) ───
  (() => {
    resetMsgCounter(7)
    return {
      persona: 'doctor' as const,
      status: 'active' as const,
      messages: [
        msg(
          'assistant',
          "Alright, let's figure out what's going on. No judgment — every project gets stuck. The question is *why*.\n\nTell me what you're building and where it hurts."
        ),
        msg(
          'user',
          "We're a fintech startup trying to build a multi-currency payment platform. We've got 5 engineers across 3 time zones and the biggest problem is nobody agrees on architecture decisions. Every meeting turns into a debate about microservices vs monolith, REST vs GraphQL, and nothing moves forward. I'm the product lead and I feel like I'm watching the team argue while our competitors ship."
        ),
        msg(
          'assistant',
          "Architecture debates that never resolve are almost never about architecture. They're about something else — usually unclear ownership, missing decision-making authority, or a team that doesn't trust each other's judgment yet.\n\nTwo questions:\n\n1. Who has the final say on technical decisions? Is there a clear tech lead or architect, or is it consensus-driven?\n2. How long has the team worked together? And did they inherit an existing codebase or start from scratch?"
        ),
      ],
    }
  })(),

  // ─── 9. Critic — abandoned (user left after opening) ───
  (() => {
    resetMsgCounter(8)
    return {
      persona: 'critic' as const,
      status: 'abandoned' as const,
      messages: [
        msg(
          'assistant',
          "Alright, show me what you've got. I'll give you my honest take — what works, what doesn't, and the thing nobody's telling you.\n\nWhat are you submitting for review?"
        ),
      ],
    }
  })(),
]
